/*
 * This file is Copyright Daniel Silverstone <dsilvers@digital-scurf.org> 2006
 */

#include <stdio.h>

/* Construct and write out the tables for the gfshare code */

int
main(int argc, char** argv)
{
  unsigned char logs[256];
  unsigned char exps[256];
  unsigned int x;
  unsigned int i;
  
  x = 1;
  for( i = 0; i < 255; ++i ) {
    exps[i] = x;
    logs[x] = i;
    x <<= 1;
    if( x & 0x100 )
      x ^= 0x11d; /* Unset the 8th bit and mix in 0x1d */
  }
  logs[0] = 0; /* can't log(0) so just set it neatly to 0 */
  exps[255] = 1; /* exp(255) simply *is* 1 */
  
  /* The above generation algorithm clearly demonstrates that
   * logs[exps[i]] == exps[logs[i]] == i
   */
  
  /* Spew out the tables */
  
  fprintf(stdout, "\
/*\n\
 * This file is autogenerated by gfshare_maketable.\n\
 */\n\
\n\
unsigned char logs[256] = {\n  ");
  for( i = 0; i < 256; ++i ) {
    fprintf(stdout, "0x%02x", logs[i]);
    if( i == 255 )
      fprintf(stdout, " };\n");
    else if( (i % 8) == 7 )
      fprintf(stdout, ",\n  ");
    else
      fprintf(stdout, ", ");
  }
  
  /* The exp table we output from 0 to 510 because that way when we
   * do the lagrange interpolation we don't have to be quite so strict
   * with staying inside the field which makes it quicker
   */
  
  fprintf(stdout, "\
\n\
unsigned char exps[510] = {\n  ");
  for( i = 0; i < 510; ++i ) {
    fprintf(stdout, "0x%02x", exps[i % 255]); /* exps[255]==exps[0] */
    if( i == 509 )
      fprintf(stdout, " };\n");
    else if( (i % 8) == 7)
      fprintf(stdout, ",\n  ");
    else
      fprintf(stdout, ", ");
  }
  
  return 0;
}

